### ISSUE TITLE
A little help with weather data collection code

### ISSUE THREAD

**Issue by krasatos** [kloggy/Home-Assistant#1]
Hey there, im back for some quick help.
I am trying to alter your code as there is no smartweather node near me.
I did find a local website which offers the `rain_today` and i scraped it to get todays weather:
```
      rain_minus0:
        friendly_name: Rain today
        value_template: "{{ states('sensor.rain_today_scrape') }}"     
        unit_of_measurement: "mm"
```

I noticed that you also use smartweather to gather yesterdays rainfall, but unfortunately i cannot get that data from the website.
```
      - service: input_number.set_value
        data_template:
          entity_id: >
            input_number.rain_minus{{ loop_count }}
          value: >
            {% if loop_count | int == 0 %}
              0 
            {% elif loop_count | int == 1 %}
              {{ states('sensor.smartweather_rain_yesterday') }} 
            {% else %}
              {{ states('input_number.rain_minus' ~ (loop_count | int - 1) | string) }}
            {% endif %}
```

Any ideas on how to use the data i have to work around this?
